#!/bin/bash

source /etc/yunohost/apps/chatonsinfos/scripts/_common.sh
source /usr/share/yunohost/helpers

[ "${YNH_APP_ID}" == "chatonsinfos" ] && exit 0

install_dir=/var/www/chatonsinfos/
ynh_secure_remove --file="$install_dir/public/${YNH_APP_ID}.properties"

sed -i "/^subs\.${YNH_APP_ID} =/d" "$install_dir/public/organization.properties"
