#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set --key=host_server_distribution --value="YunoHost"

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir/sources"
mkdir $install_dir/public

# Empty html page to fix the CI
echo "<html><body>ChatonsInfos</body></html>" > $install_dir/public/index.html

chown -R $app:$app "$install_dir"
chown $app:www-data "$install_dir"
chown -R $app:www-data "$install_dir/public"
chmod -R o-rwx "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

cp "$install_dir/sources/MODELES/organization.properties" "$install_dir/public/"
orga_path="$install_dir/public/organization.properties"

ynh_write_var_in_file --file="$orga_path" --key="file.datetime" --value="$(date '+%Y-%m-%dT%H:%M:%S')"
ynh_write_var_in_file --file="$orga_path" --key="file.generator" --value="chatonsinfos_ynh"

chown -R $app:www-data "$install_dir/public"

#=================================================
# GENERATE CONFIG PANEL
#=================================================
ynh_script_progression "Generating configuration panel..."

generate_config_panel

chmod 400 "$install_dir/public/organization.properties"
chown $app:www-data "$install_dir/public/organization.properties"
ynh_store_file_checksum "$install_dir/public/organization.properties"

#=================================================
# ADD A CRON JOB
#=================================================
ynh_script_progression "Adding cron job to generate metrics..."

cron_path="/etc/cron.daily/$app"
ynh_config_add --template="cron" --destination="$cron_path"
chown root: "$cron_path"
chmod 644 "$cron_path"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
