#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# "REBUILD" THE APP (DEPLOY NEW SOURCES, RERUN NPM BUILD...)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir/sources"

chown -R $app:$app "$install_dir"
chown $app:www-data "$install_dir"
chown -R $app:www-data "$install_dir/public"
chmod -R o-rwx "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

#=================================================
# RECONFIGURE THE APP (UPDATE CONF, APPLY MIGRATIONS...)
#=================================================
# GENERATE CONFIG PANEL
#=================================================
ynh_script_progression "Generating configuration panel..."

generate_config_panel

chmod 400 "$install_dir/public/organization.properties"
chown $app:www-data "$install_dir/public/organization.properties"
ynh_store_file_checksum "$install_dir/public/organization.properties"

#=================================================
# ADD A CRON JOB
#=================================================
ynh_script_progression "Adding cron job to generate metrics..."

cron_path="/etc/cron.daily/$app"
ynh_config_add --template="cron" --destination="$cron_path"
chown root: "$cron_path"
chmod 644 "$cron_path"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
